<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-us">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="TaoWang" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    <title>理解javascript promise</title>
    
    <link rel="shortcut icon" href="/favicon.ico">
    <link href="/atom.xml" rel="alternate" title="奔跑的蚂蚁" type="application/atom+xml" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/media/css/style.css">
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/retina.js/1.3.0/retina.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/github.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
    <script type="text/javascript"> hljs.initHighlightingOnLoad(); </script>
  </head>
  <body>
      <div id="main" role="main">
        <header>
          <div id="header">
            <h1><a title="奔跑的蚂蚁" class="" href="/">奔跑的蚂蚁</a></h1>
          </div>
          <nav>
            
            <span><a title="Archive" href="/archive.html"><i class="fa fa-list-ul"></i></a></span>
            
            <span><a title="Tags" href="/tags.html"><i class="fa fa-tags"></i></a></span>
            
            <span><a title="About" href="/about.html"><i class="fa fa-user"></i></a></span>
            
          </nav>
        </header>
        <div id="content">
        <article>
  <section class="title">
    <h2>理解javascript promise </h2>
  </section>
  <section class="meta">
  <span class="time">
    <time datetime="2016-03-04">2016-03-04</time>
  </span>
  
  <span class="tags">
    
    <a href="/tags.html#promise" title="promise">#promise</a>
    
    <a href="/tags.html#javascript" title="javascript">#javascript</a>
    
  </span>
  
  </section>
  <section class="post">
  <h3>so promise ？</h3>

<p>promise，翻译过来就是承诺的意思，在javascript中，promise是一个关于异步操作的结果的“承诺”,
可以在<a href="https://promisesaplus.com/">promise A+ spec</a>中了解更多关于promise的信息。</p>

<p>在此翻译了pouchdb中关于promise的博客，以加深对promise的理解。<a href="https://twitter.com/nolanlawson">作者</a>在推上发了一段关于promise的代码，如下:</p>

<pre><code class="javascript">//case 1
doSomething().then(function() {
    return doSomethingElse()
})
//case 2
doSomething().then(function() {
    doSomethingElse()
})
//case 3
doSomething().then(doSomethingElse())
//case 4
doSomething().then(doSomethingElse)
</code></pre>

<p>注意: <code>doSomething</code>及<code>doSomethingElse</code>都是一个函数并返回新的promise.</p>

<p>知道几个case的区别么? #@!...以下代码可能会使用一些ES6语法。</p>

<h3>坑1: 回调金字塔</h3>

<pre><code class="javascript">getUsersFromRESTAPI().then((resultOfUsers) =&gt; {
    resultOfUsers.forEach((user) =&gt; {
        localStorageWithPromise.put(user).then(() =&gt; {
            console.log(`put user ${user.name} to localStorage success!`)
        }).catch((err) =&gt; {
            console.log(`put user ${user.name} to localStorage failed!`)
            localStorageWithPromise.remove(user.id).then(() =&gt; {
                console.log(`remove possible user info with user id : ${user.id}`)
            })
            ...
        })
    })
})
</code></pre>

<p>这样当我们需要完成更复杂的一些回调操作时，可能代码比这还嵌套得深，这样代码的可读性以及可维护性就会很糟糕，而更好的书写
方式应该这样，称为<code>组合promise</code></p>

<pre><code class="javascript">getUsersFromRESTAPI().then(resultOfUsers =&gt; {
    return Promise.all(resultOfUsers.forEach((user) =&gt; {
        return localStorageWithPromise.put(user)
    }))
}).then((resultInfo) =&gt; {
    console.log(`put result ${resultInfo}`)
}).catch((err) =&gt; {
    console.log(err)
})
</code></pre>

<p>更直观一点，或许我们应该组织我们的promise调用链如下面这样的方式：</p>

<pre><code class="javascript">operationA().then((resultOfA) =&gt; {
    return doWithResultA(resultOfA)
}).then((resultFromA) =&gt; {
    return operationB(resultFromA)
}).then((resultFromB) =&gt; {
    return operationC(resultFromB)
}).catch(err =&gt; {
    console.log(`any errors "${err}" happened in promise chain`)
})
</code></pre>

<p>这样整个调用链会比较清晰，且可以统一的<code>catch</code>错误并处理。</p>

<h3>坑2: forEach与promise</h3>

<p>比如如下的操作:</p>

<pre><code class="javascript">getUsersFromRESTAPI().then(resultOfUsers =&gt; {
    resultOfUsers.forEach(user =&gt; {
        user.remove()
    })
}).then(() =&gt; {
    //以为已经删除了所有用户
})
</code></pre>

<p>很多时候我们以为这样写就可以了，其实是错误的，第二个then回调并不会等待所有user被删除才执行，因为在第一个then回调中，函数返回
的是<code>undefined</code>, 所以这样的写法就会存在bug, 正确的写法应该如下:</p>

<pre><code class="javascript">getUsersFromRESTAPI().then(resultOfUsers =&gt; {
    return Promise.all(resultOfUsers.forEach(user =&gt; {
        return user.remove()
    }))
}).then(() =&gt; {
    console.log("all users has been deleted.")
})
</code></pre>

<p>在第一个then回调中返回了promise，并使用了<code>promise.all</code>, 注意<code>user.remove</code>也是返回promise的。</p>

<h3>坑3: 忘记catch错误</h3>

<p>我们不应该去假设我们的promise不返回任何错误，应该在promise调用中都进行正确的错误处理.</p>

<pre><code class="javascript">promise1().then(() =&gt; {
    return opReturnPromise2()
}).then(() =&gt; {
    return opReturnPromise3()
}).catch(err =&gt; {
    //handle errors properly.
})
</code></pre>

<h3>promise中的返回值</h3>

<pre><code class="javascript">promise1().then(() =&gt; {
    opReturnPromise2()
}).then(() =&gt; {
    opReturnPromise3()
}).catch(err =&gt; {
    //handle errors properly.
})
</code></pre>

<p>有什么问题么？这儿在promise的回调中<code>返回值存在问题</code>, 在promise中，then()回调可以返回:</p>

<ol>
<li>返回另一个promise.</li>
<li>返回一个值(或者undefined).</li>
<li>返回一个错误.</li>
</ol>


<h4>返回另一个promise</h4>

<p>这就是上面提到的<code>组合promise</code>.</p>

<pre><code class="javascript">promise1().then(() =&gt; {
    return opReturnPromise2()
}).then(() =&gt; {
    return opReturnPromise3()
}).catch(err =&gt; {
    //handle errors properly.
})
</code></pre>

<h4>返回一个值(或者undefined)</h4>

<pre><code class="javascript">getUserFromRESTAPI(userName).then((userInfo) =&gt; {
    if (FriendsCache[userInfo.id]) {
        return FriendsCache[userInfo.id]
    }
    return getUserFriends(userInfo.id)
}).then((friends) =&gt; {
    console.log(friends)
}).catch(err =&gt; {
    console.log(err)
})
</code></pre>

<p>这样写是不是很清晰，在第二个处理friends的then回调中，我不需要关心friends是在cache中还是从API中获取的，处理得到的好友列表即可。
由于在javascript中，函数不显视的返回任何值，则返回undefined，所有在promise的then回调中，建议总是返回一个值或者抛出错误。</p>

<h4>返回一个错误</h4>

<pre><code class="javascript">getUserFromRESTAPI(userName).then((userInfo) =&gt; {
    if (isLoggedout(userInfo.id)) {
        throw new Error("logged out!")
    }
    if (FriendsCache[userInfo.id]) {
        return FriendsCache[userInfo.id]
    }
    return getUserFriends(userInfo.id)
}).then((friends) =&gt; {
    console.log(friends)
}).catch(err =&gt; {
    console.log(err)
})
</code></pre>

<h3>巧用Promose.resolve</h3>

<p>使用promise包装同步的代码使其异步化，并进行错误处理。对于同步的操作，promise也可以提供很多帮助，比如:</p>

<pre><code class="javascript">let caculateSomethingAndMayThrowError  = (x, y) =&gt; {
    if (x &lt; y) {
        throw new Error("x &lt; y")
    }
    return x - y
}

let wrapAPI2Promise = () =&gt; {
    return Promise.resolve().then(() =&gt; {
        let value = caculateSomethingAndMayThrowError()
        return value
    }).then((value) =&gt; {
        console.log(value)
    }).catch((err) =&gt; {
        console.log(err)
    })
}
</code></pre>

<p>在catch中我们可以处理同步函数抛出的异常.</p>

<h3>避免reject函数，使用catch</h3>

<p>catch函数其实是一个语法糖, 如下所示:</p>

<pre><code class="javascript">promise1().catch((err) =&gt; {})
//equal to
promise1().then(null, (err) =&gt; {})
</code></pre>

<p>但是如下的代码却并不一样，如下:</p>

<pre><code class="javascript">promise1().then(() =&gt; {
    return promise2()
}).catch((err) =&gt; {
    console.log(err)
})

promise1().then(() =&gt; {
    return promise2()
}, (err) =&gt; {
    console.log(err)
})
</code></pre>

<p>第一个catch会处理整个promise链中的异常错误，但是第二个却是处理promise1的异常错误，因为它相当于promise1的reject函数。
所以一般情况下建议只用catch函数，避免给then传递第二个参数导致理解错误，出现bug。</p>

<h3>promise工厂函数</h3>

<p>有时可以通过工厂函数，组合我们的promise链，但是一定要注意返回值, 例如:</p>

<pre><code class="javascript">//依次sleep 1s

let suspendOneSecondFactory = () =&gt; {
    return () =&gt; {
        return new Promise((resolve, reject) =&gt; {
            setTimeout(() =&gt; {
                console.log('sleep 1s')
                resolve()
            }, 1000)
        })
    }
}

let result = Promise.resolve()
[1, 2, 3].forEach(() =&gt; {
    result = result.then(suspendOneSecondFactory())
})
result.then(() =&gt; {
    console.log("the end")
}).catch(err =&gt; {
    console.log(err)
})
</code></pre>

<h3>总结</h3>

<p>promise在使用时一定要注意then回调的返回值，以及组合使用promise，并将操作尽量步骤化，那样可以使用proise链组合出各种需要的
依赖链并进行调用, 如果给then调用传递非函数值，在then调用中传递的非函数值会被解析为null。</p>

  </section>
  
</article>

        </div>
        <footer>
          <div>
            
            &copy; 2015 ~ 2016 TaoWang | powered by jekyll | themed by <a href="http://lhzhang.com" title="sext vi">sext vi</a>
          </div>
        </footer>
      </div> <!-- main -->
  </body>
</html>
